### ISSUE TITLE
[tox] astropy should be listed at "package versions" section rather than at the top

### ISSUE THREAD

**Issue by bsipocz** [astropy/pytest-astropy-header#27] opened 2020-11-08 08:22 UTC
This is not really a pytest-astropy-header issues, but an issue for a lot of coordinated/affiliated packages. E.g. astruqery uses the header properly, it's astroquery's version listed at the top, but other packages have astropy's version there rather than their own. 
So the task here is to go through those coordinated packages and fix them, e.g. with batchpr.

E.g. this is expected:

```
platform darwin -- Python 3.8.0, pytest-6.0.1, py-1.9.0, pluggy-0.13.1

Running tests with astroquery version 0.4.2.dev6444_testrun.
Running tests in astroquery docs.

Date: 2020-11-07T23:21:54

Platform: macOS-10.13.6-x86_64-i386-64bit

Executable: /Users/bsipocz/.pyenv/versions/3.8.0/bin/python

Full Python Version: 
3.8.0 (default, Dec 26 2019, 15:55:54) 
[Clang 10.0.0 (clang-1000.11.45.5)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Matplotlib: 3.3.2
Astropy: 4.2rc1
APLpy: not available
pyregion: not available
pyVO: 1.1
astropy-helpers: 4.0.1

Using Astropy options: remote_data: none.
```

But this is what I see:

```
Running tests with Astropy version 4.2rc1.
Running tests in reproject docs.

Date: 2020-11-07T23:32:17

Platform: macOS-10.13.6-x86_64-i386-64bit

Executable: /Users/bsipocz/.pyenv/versions/3.8.0/bin/python3.8

Full Python Version: 
3.8.0 (default, Dec 26 2019, 15:55:54) 
[Clang 10.0.0 (clang-1000.11.45.5)]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.19.2
Scipy: 1.5.2
Matplotlib: 3.3.2
h5py: 2.10.0
Pandas: 0.25.3

Using Astropy options: remote_data: none.
```

Packages with this problem include, but not limited to: reproject, photutils, regions

**Comment by pllim** [comment] 2020-11-09 19:57
I thought @larrybradley said he fixed it for photutils, except when running things with `tox`, see astropy/photutils#1046 .

Could this be a duplicate of astropy/package-template#439 ?

**Comment by larrybradley** [comment] 2020-11-09 20:08
I didn't fix anything.  My test showed it works fine when running `pytest` locally, but not with `tox`.  The CI uses `tox`, so this is still a frustration.

**Comment by bsipocz** [comment] 2020-11-09 21:50
Oh, I didn't search for issues outside this repo, merely tried to report all the things I run into while cutting the RC.

**Comment by pllim** [comment] 2020-12-04 14:01
This remains a confusing bug. I see that it doesn't work for some people using `tox` but it works properly when one of my simpler package uses this and `tox`. Not sure what is causing it.

**Comment by pllim** [comment] 2020-12-04 14:03
Closing as duplicate of #15

**Closed as completed by pllim** 2020-12-04 14:03 UTC
Labels: bug, duplicate
