### ISSUE TITLE
Show astropy as part of the HEADER_MODULES

### ISSUE THREAD

**Issue by mhvk** [astropy/pytest-astropy-header#17] opened 2020-01-30 01:44 UTC
For packages other than astropy, astropy is a dependency just like all the others, so I think it makes sense to have it included as part of `PYTEST_HEADER_MODULES` under "package versions" rather than listed separately away from those, as in:
```
======================================== test session starts =========================================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1

Running tests with Astropy version 4.0.
Running tests in baseband docs.
```

**Comment by mhvk** [comment] 2020-01-30 01:53
Actually, investigating further, the reason that the first line is wrong is that the cookiecutter template does not have a `conftest.py` in the top directory. If I put that there, that line becomes correct. But I have to manually add astropy to `PYTEST_HEADER_MODULES`, which seems strange.

**Comment by pllim** [comment] 2020-01-30 16:00
Is this related to #15 or something different?

**Comment by mhvk** [comment] 2020-01-30 16:12
Indeed, I think #15 reflects that without `astropy_helpers` the `conftest` inside the package is not used at all.

**Comment by pllim** [comment] 2020-01-30 16:18
cc @weaverba137

**Comment by weaverba137** [comment] 2020-01-30 17:59
That is mostly consistent with what I observed, except that when I ran a *coverage* test, then the `conftest.py` file inside the package *did* get used.

**Comment by pllim** [comment] 2020-12-04 14:04
Closing as duplicate of #15

**Closed as completed by pllim** 2020-12-04 14:04 UTC
